#! /bin/bash

#AUTOSTART
sxhkd &
numlockx &
nitrogen --restore &
~/.config/polybar/launch.sh
picom &
xsetroot -cursor_name left_ptr &
~/.screenlayout/display.sh
# nzxt
coolercontrol &
# Network Applet
nm-applet --indicator &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Notifications
/usr/bin/dunst &


#WORKSPACES
bspc monitor -d                   

#FRAMES AND GAPSE
bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"

#SPACE COLOR WHEN SELECTING A NEW WINDOW POSITION
bspc config presel_feedback_color "fd2e59"

#YOU CAN MAKE GAPS ONLY BETWEEN WINDOWS WITH THE HELP OF THIS Crap
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))

#SPLITTING COEFFICIENT, HOW MANY PERCENTAGE WILL REMAIN FROM THE PARENT WINDOW WHEN OPENING A NEW
bspc config split_ratio          0.5

#WINDOW FOCUS BY CURSOR Hover
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#MONOCLE MODE WHEN ONE WINDOW IS OPEN
bspc config single_monocle	     false

#DISABLE FRAME AND PADDING GAPS WHEN ONE WINDOW IS OPEN
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

#SCHEMES ACCORDING TO WHICH WINDOWS WILL OPEN
#bspc config automatic_scheme	spiral

#WINDOW RULES
bspc rule -a Firefox state=floating rectangle=1350x900+50+90 desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
bspc rule -a Inkscape desktop='^3'
bspc rule -a Blender desktop='^2'